/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BugTracker: typeof import('./src/components/BugTracker.vue')['default']
    CatBackground: typeof import('./src/components/CatBackground.vue')['default']
    CatSprite: typeof import('./src/components/CatSprite.vue')['default']
    ClickPaw: typeof import('./src/components/ClickPaw.vue')['default']
    EasterEgg: typeof import('./src/components/EasterEgg.vue')['default']
    LangSwitch: typeof import('./src/components/LangSwitch.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NModal: typeof import('naive-ui')['NModal']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
    XpBadge: typeof import('./src/components/XpBadge.vue')['default']
  }
}
