/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BugTracker: typeof import('./src/components/BugTracker.vue')['default']
    CatAvatar: typeof import('./src/components/CatAvatar.vue')['default']
    CatAvatarSVG: typeof import('./src/components/CatAvatarSVG.vue')['default']
    CatBackground: typeof import('./src/components/CatBackground.vue')['default']
    EasterEgg: typeof import('./src/components/EasterEgg.vue')['default']
    LangSwitch: typeof import('./src/components/LangSwitch.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NEmpty: typeof import('naive-ui')['NEmpty']
    NModal: typeof import('naive-ui')['NModal']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NSpace: typeof import('naive-ui')['NSpace']
    NStatistic: typeof import('naive-ui')['NStatistic']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ThemeSwitch: typeof import('./src/components/ThemeSwitch.vue')['default']
  }
}
