"""Shared scaffolding helpers for dev-style agents.

These agents don't yet call an LLM — they produce a real on-disk artifact
(a stub file at the path declared by the task DoD, or a default scratch
location). This is explicitly a skeleton: it's honest about not generating
real code, but it DOES write a real file so that downstream verification,
Review Agent, and the task state machine all see an actual artifact.

Swap `_write_stub` for a real LLM call when the Adapter supports it.
"""

from __future__ import annotations

import asyncio
import json
import os
from datetime import datetime, timezone
from pathlib import Path


STUB_HEADER = {
    "core_dev": "// Core dev stub — generated by CatCoding skeleton pipeline\n",
    "frontend": "<!-- Frontend stub — generated by CatCoding skeleton pipeline -->\n",
    "backend":  "# Backend stub — generated by CatCoding skeleton pipeline\n",
}


def default_artifact_path(role: str, workdir: str, task_id: str | None) -> str:
    """Pick a deterministic scratch file when the task has no declared output_path."""
    suffix = {
        "core_dev": ".rs",
        "frontend": ".vue",
        "backend":  ".py",
    }.get(role, ".txt")
    safe_task = (task_id or "unassigned")[:8]
    return os.path.join(workdir, ".catcoding", "scaffold", f"{role}-{safe_task}{suffix}")


async def scaffold_task(agent, msg, progress_steps: list[str]) -> None:
    """Run `progress_steps` and write a real stub file at the end.

    Each step is sent as a progress event and takes ~0.3s of real time so the
    Watchdog heartbeat pipeline has something to observe. The artifact is
    always written to disk — caller's DoD.validate() can then check it exists.
    """
    role = agent.role
    out_path = default_artifact_path(role, agent.workdir, msg.task_id)
    Path(out_path).parent.mkdir(parents=True, exist_ok=True)

    total = len(progress_steps)
    for i, step in enumerate(progress_steps, start=1):
        pct = int(i * 100 / total)
        agent._send_progress(msg.task_id, pct, step)
        await asyncio.sleep(0.3)

    content = (
        STUB_HEADER.get(role, f"// {role} stub\n")
        + f"// role: {role}\n"
        + f"// agent_id: {agent.agent_id}\n"
        + f"// task_id: {msg.task_id}\n"
        + f"// title: {msg.summary}\n"
        + f"// generated_at: {datetime.now(timezone.utc).isoformat()}\n"
        + f"// project: {agent.project_id}\n"
        + "//\n"
        + "// NOTE: this is a scaffold. CatCoding skeleton pipeline wrote a\n"
        + "//       deterministic placeholder so the task produces a real\n"
        + "//       on-disk artifact. Hook an LLM adapter into the agent to\n"
        + "//       generate actual code here.\n"
    )
    Path(out_path).write_text(content, encoding="utf-8")
    agent._log(f"📝 wrote scaffold artifact: {out_path}")

    # Emit a machine-readable manifest so Review/Test agents can find it.
    manifest = {
        "role": role,
        "agent_id": agent.agent_id,
        "task_id": msg.task_id,
        "title": msg.summary,
        "artifact": out_path,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "kind": "scaffold",  # explicit: not real LLM output
    }
    manifest_path = os.path.join(
        agent.workdir, ".catcoding", "scaffold", f"{role}-{(msg.task_id or 'none')[:8]}.json"
    )
    Path(manifest_path).parent.mkdir(parents=True, exist_ok=True)
    Path(manifest_path).write_text(json.dumps(manifest, indent=2, ensure_ascii=False))
